// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIGASFL.Entities
{
    public partial class TwoFactorAuthenticator
    {
        public TwoFactorAuthenticator()
        {
            UserTfacross = new HashSet<UserTfacross>();
            UserTfaverifiedCode = new HashSet<UserTfaverifiedCode>();
        }

        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Enabled { get; set; }
        public short? OrderBy { get; set; }
        public DateTime CreatedDate { get; set; }

        public virtual ICollection<UserTfacross> UserTfacross { get; set; }
        public virtual ICollection<UserTfaverifiedCode> UserTfaverifiedCode { get; set; }
    }
}