// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIGASFL.Entities
{
    public partial class UserSecurityQuestion
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public int? QuestionId1 { get; set; }
        public string QuestionCustom1 { get; set; }
        public string Answer1 { get; set; }
        public int? QuestionId2 { get; set; }
        public string QuestionCustom2 { get; set; }
        public string Answer2 { get; set; }
        public int? QuestionId3 { get; set; }
        public string QuestionCustom3 { get; set; }
        public string Answer3 { get; set; }
    }
}