// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SIGASFL.Entities
{
    public partial class UserProfile
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName1 { get; set; }
        public string LastName2 { get; set; }
        public string NickName { get; set; }
        public string Gender { get; set; }

        public virtual Users User { get; set; }
    }
}